name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # If you need node for a build step, you can enable this. For plain static files it's optional.
    - name: Setup Node.js (optional)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Configure Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact for deployment (project subfolder)
      uses: actions/upload-pages-artifact@v1
      with:
        # Publish the project folder that contains index.html
        path: "독케익성대모사팬게임"

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
